name: "Test"
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23.1"

          # Create a dummy dist folder
      - name: Mock dist folder
        run: |          
          mkdir -p dist
          touch dist/index.html

      - run: go test -coverprofile=coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
